### ISSUE TITLE
Option for default variants

### ISSUE THREAD

**Issue by daniel-de-wit** [czim/laravel-paperclip#23]
Next to have a fallback variant configuration it might be nice to have default variant options.

For example, in my project I would like to have thumbnails of a standard size.

**Comment by czim** [comment]
The current functionality is (and I take it that you mean this by 'fallback configuration'): if a model does *not* have any variants configured, the *default* configured variants will be used. If any variant is configured, the defaults are entirely overridden/ignored.

And the feature request here is that you'd want to have a default variant to be included in a Model's configured variant list, regardless of whether it has variants of its own configured?

If so... the reason it is not currently handled this way is because of lack of control: if you want to exclude/override a default variant for only one model, you'd have to remove it from the defaults and include it specifically in every model's variant configuration.

I'd rather look for a way to keep the same (or a better) degree of control as in the current situation. Perhaps if the specific Model configuration would have `[ 'variantName' => false ]` set, it would negate the default variant by that name. 
This would still be a breaking change though, so it would also require a configuration flag to toggle the old behaviour (default) and the 'overriding' behaviour.

Would that work for your use-case?

**Comment by daniel-de-wit** [comment]
That sounds like a good solution to me.

In my use case having to manually set / edit the 'cms_thumbnail' on each model is not really "dry".

**Comment by czim** [comment]
This is now included in `2.6.0`. It works as described above, including the ability to 'disable' a global default variant by setting the variant configuration for a specific attachment to a literal `false`.
