### ISSUE TITLE
How to make use of the hooks to optimise images.

### ISSUE THREAD

**Issue by kyranb** [czim/laravel-paperclip#24]
I've had a look at the hook functionality and the interface that goes with it but I'm not exactly sure which public method can be used to access the underlying file in the storage? 

I was hoping to be able to link paperclip with this https://github.com/spatie/laravel-image-optimizer
so that the original image file is saved, but after resizing variants they are optimised (or ideally doing it all in one go).

Any help would be much appreciated =)

**Comment by czim** [comment]
Hmm. There are two ways you can do this:

1. The `$model->{attachment}->url()` method should give you the public URL, which you can 'translate' into a local path if your storage solution is consistent. I don't think there is a clean, direct way of getting an 'internal' URL through Paperclip (especially since storage need not be local in any case).
Since the default URL is that of the original file, you should be able to modify that, write it back. This would not affect other variants, of course -- and I'm not sure whether that's what you're asking for..

2. You can make your own variant, and call it 'optimized' f.i. You can write your own variant strategy and make that use the Spatie image optimizer. This is the cleanest approach I can think of and has the added benefit of keeping a non-optimized version of the image.

But maybe I'm misreading your issue, so please let me know what you think, or why your use-case would not be served by the above approaches.

**Comment by kyranb** [comment]
Thanks for the insight :)

2 Definitely sounds like the best solution. Would you be open to a PR for an image optimiser strategy as part of FileHandling, or is that outside of its scope?

**Comment by kyranb** [comment]
I've just added a PR to `file-handling` that is framework agnostic.

https://github.com/czim/file-handling/pull/6
