### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by czim** [czim/laravel-paperclip#29]
The documentation has some flaws and it shouldn't depend on Stapler's documentation anymore. It will need to be made complete, and provide clear instructions for those that have no experience with Stapler.

**Comment by rossbearman** [comment]
Note for the documentation on another minor difference from Stapler:

Stapler supported passing a string containing a file path to an attachment attribute in order to set the file at that path as the attachment. Paperclip's behaviour when passed a string is to create a `.txt` file with a 16-character hash as it's name with the passed string as it's content (via `makeFromRawData()` in the `StorableFileFactory`).

**Comment by czim** [comment]
Documentation has been slightly improved. Still needs work.
