### ISSUE TITLE
attaching via url with url encoded filenames is problematic

### ISSUE THREAD

**Issue by kimchirichie** [czim/laravel-paperclip#64]
this will not work because the url is interpreted as `raw` datatype instead of `uri`:
```
$photo->image = "https://my-domain.com/filename_with space.jpeg";
$photo->save();
```

so i tried the following:
```
$filename = urlencode("filename_with space.jpeg");
$photo->image = "https://my-domain.com/${$filename}";
$photo->save();
```

which uploads to S3 fine, but then saves the filename with encoded filename. this is problematic because S3 will not recognize this resource.

**Comment by czim** [comment]
Setting plain text directly on the attribute is always tricky, because it is technically ambiguous.

You may use [this more controlled approach](https://github.com/czim/laravel-paperclip#setting-attachments-without-uploads) if you handle the downloading of the files yourself.

I'm considering a rewrite of paperclip that will definitely address this and many other downsides of the current approach, but no ETA on that for now.

**Comment by kimchirichie** [comment]
I've made the following changes:
```
$file = app(StorableFileFactory::class)->makeFromUrl($this->fileUrl);
$this->photo->image = $file;
$this->photo->save();
```
Now, it works as expected.
